swagger: "2.0"
info:
  version: "0.0.1"
  title: IPA-API
host: the-ipa-api.herokuapp.com
# basePath prefixes all resource paths
basePath: /ipa-api
#
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    x-swagger-router-controller: users
    post:
      description: Creates new account
      operationId: createAccount
      parameters:
        - name: user
          in: body
          description: user to add to the database
          required: true
          schema:
            $ref: '#/definitions/CreateUser'
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CreateUserSuccess"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /search:
    x-swagger-router-controller: search
    get:
      description: Returns a specific beer from brewerydb
      operationId: searchBeer
      parameters:
      - name: name
        in: query
        description: The name of the beer that was searched
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SearchBeer"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /beers:
      x-swagger-router-controller: beers
      post:
        description: Adds a beer to the database
        operationId: addBeer
        parameters:
          - name: beer
            in: body
            description: beer to add to the database
            required: false
            schema:
              $ref: '#/definitions/AddBeerRequest'
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/AddBeerResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /favorites:
    x-swagger-router-controller: favorites
    get:
      description: Returns a list favorites of a client
      operationId: returnFavorites
      parameters:
        - name: user_id
          in: query
          description: the favorite beers of the client
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetFavoritesResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Adds a new beer to a clients list of favorites
      operationId: addFavorite
      parameters:
        - name: favorite
          in: body
          description: information on the favorite beer of the client
          required: true
          schema:
            $ref: "#/definitions/AddFavoriteRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AddFavoriteResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: delete a beer from list of favorites
      operationId: deleteFromFavorites
      parameters:
        - name: id
          description: user_beers id
          type: integer
          in: query
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DeleteFavoriteBeerResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /favorite:
    x-swagger-router-controller: favorite
    get:
      description: returns more detailed information about a specific favorite beer
      operationId: specificFavorite
      parameters:
        - name: id
          in: query
          description: detailed information on this specific beer
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SpecificFavoriteBeer"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  CreateUser:
    type: object
    required:
      - first_name
      - last_name
      - username
      - email
      - password
    properties:
      first_name:
        type: string
        description: first name of new user
      last_name:
        type: string
        description: last name of new user
      username:
        type: string
        description: username
      email:
        type: string
        description: email
      password:
        type: string
        description: password
  CreateUserSuccess:
    type: object
    required:
      - first_name
      - last_name
      - username
      - email
    properties:
      first_name:
        type: string
        description: first name of new user
      last_name:
        type: string
        description: last name of new user
      username:
        type: string
        description: username
      email:
        type: string
        description: email
  AddBeerRequest:
      type: object
      required:
        - bdb_id
        - name
        - abv
        - ibu
        - label_url
        - description
        - type_name
      properties:
        bdb_id:
          type: string
        name:
          type: string
        abv:
          type: string
        ibu:
          type: string
        label_url:
          type: string
        description:
          type: string
        type_name:
          type: string
  AddBeerResponse:
      type: object
      required:
        - id
        - bdb_id
        - name
        - abv
        - ibu
        - label_url
        - description
        - type_name
      properties:
        id:
          type: integer
        bdb_id:
          type: string
        name:
          type: string
        abv:
          type: number
        ibu:
          type: integer
        label_url:
          type: string
        description:
          type: string
        type_name:
          type: string
  GetFavoritesResponse:
    required:
      - beers
    properties:
      beers:
        type: array
        items:
          type: object
          properties:
            rating:
              type: integer
              description: beer rating
            id:
              type: integer
              description: the users_beers id
            comment:
              type: string
              description: the users comment on the beer
            name:
              type: string
              description: the beers name
            label_url:
              type: string
              description: the label url
  AddFavoriteRequest:
    type: object
    required:
      - rating
      - comment
      - user_id
      - beer_id
    properties:
      rating:
        type: integer
        description: The users chosen rating of the beer(1-5)
      comment:
        type: string
        description: The users comment about the beer
      user_id:
        type: integer
        description: user id of client adding new favorite
      beer_id:
        type: integer
        description: serial id of beers table for new favorite
  AddFavoriteResponse:
    type: object
    required:
      - rating
      - comment
      - user_id
      - beer_id
    properties:
      rating:
        type: integer
        description: The users chosen rating of the beer(1-5)
      comment:
        type: string
        description: The users comment about the beer
      user_id:
        type: integer
        description: user id of client adding new favorite
      beer_id:
        type: integer
        description: serial id of beers table for new favorite
  DeleteFavoriteBeerResponse:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        description: serial id of favorite deleted
      name:
        type: string
  SpecificFavoriteBeer:
    type: object
    required:
      - id
      - name
      - abv
      - ibu
      - label_url
      - description
      - type_name
      - rating
      - comment
    properties:
      id:
        type: integer
      name:
        type: string
      abv:
        type: number
      ibu:
        type: integer
      label_url:
        type: string
      description:
        type: string
      type_name:
        type: string
      rating:
        type: integer
      comment:
        type: string
  SearchBeer:
    required:
      - beers
    properties:
      beers:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            abv:
              type: string
            ibu:
              type: string
            label_url:
              type: string
            description:
              type: string
            type_name:
              type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
